package httpapi

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	generatedBegin  = "# BEGIN generated-route-table\n"
	generatedEnd    = "# END generated-route-table\n"
	generatedBanner = "# Generated by `go run ./cmd/genroutes`. Do not edit.\n"
)

// RenderOpenAPI builds the published spec from the route table.
// document is info and servers only. components is the schema library
// (schemas, responses, parameters, pathItems) and is not a route list.
// Every path is emitted from routes: ops collections are $ref path items,
// and every other operation is a stub with no examples. The published
// openapi.yaml is not an input, so a hand edit of that file cannot survive
// a regenerate.
func RenderOpenAPI(routes []Route, document, components []byte) ([]byte, error) {
	docText, err := normalizeDocument(document)
	if err != nil {
		return nil, err
	}
	compText, err := normalizeComponents(components)
	if err != nil {
		return nil, err
	}
	groups, err := groupByOpenAPIPath(routes)
	if err != nil {
		return nil, err
	}
	if err := assertPathItemRefs(groups, compText); err != nil {
		return nil, err
	}
	ext, err := renderRouteExtensions(routes)
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	b.WriteString(generatedBanner)
	b.WriteString(docText)
	b.WriteString(ext)
	b.WriteString("paths:\n")
	for _, g := range groups {
		block, err := renderGeneratedPath(g)
		if err != nil {
			return nil, err
		}
		b.WriteString(block)
		if !strings.HasSuffix(block, "\n") {
			b.WriteByte('\n')
		}
	}
	b.WriteString(compText)
	return []byte(b.String()), nil
}

// RenderProxyAllowlist renders the browser identity-proxy allowlist.
// Only ProxyBrowser routes are included. Parameter match kinds:
// uuid (default), segment ({key}), trigger ({triggerId}: UUID or wh_ public id).
func RenderProxyAllowlist(routes []Route) ([]byte, error) {
	type group struct {
		pattern []string
		methods []string
		auth    AuthClass
		params  map[string]string
	}
	var order []string
	groups := map[string]*group{}
	for _, rt := range routes {
		if rt.Proxy != ProxyBrowser {
			continue
		}
		segs := proxySegments(rt)
		params := paramKinds(segs)
		key := strings.Join(segs, "/")
		g := groups[key]
		if g == nil {
			g = &group{pattern: segs, auth: rt.Auth, params: params}
			groups[key] = g
			order = append(order, key)
		}
		if g.auth != rt.Auth {
			return nil, fmt.Errorf("proxy pattern %s mixes auth %s and %s", key, g.auth, rt.Auth)
		}
		g.methods = append(g.methods, rt.Method)
	}

	var b strings.Builder
	b.WriteString("// Code generated by `go run ./cmd/genroutes` from the API route table. DO NOT EDIT.\n\n")
	b.WriteString("export type ProxyAuth = \"public\" | \"embed\" | \"authenticated\";\n\n")
	b.WriteString("export type ProxyParam = \"uuid\" | \"segment\" | \"trigger\";\n\n")
	b.WriteString("export type GeneratedProxyRoute = {\n")
	b.WriteString("  readonly methods: readonly string[];\n")
	b.WriteString("  readonly pattern: readonly string[];\n")
	b.WriteString("  readonly auth: ProxyAuth;\n")
	b.WriteString("  readonly params: Readonly<Record<string, ProxyParam>>;\n")
	b.WriteString("};\n\n")
	b.WriteString("export const GENERATED_PROXY_ROUTES: readonly GeneratedProxyRoute[] = [\n")
	for _, key := range order {
		g := groups[key]
		b.WriteString("  {\n")
		b.WriteString("    methods: [")
		for i, m := range g.methods {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", m)
		}
		b.WriteString("],\n")
		b.WriteString("    pattern: [")
		for i, p := range g.pattern {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", p)
		}
		b.WriteString("],\n")
		fmt.Fprintf(&b, "    auth: %q,\n", g.auth)
		b.WriteString("    params: {")
		names := make([]string, 0, len(g.params))
		for name := range g.params {
			names = append(names, name)
		}
		sort.Strings(names)
		for i, name := range names {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%s: %q", name, g.params[name]))
		}
		b.WriteString("},\n")
		b.WriteString("  },\n")
	}
	b.WriteString("];\n")
	return []byte(b.String()), nil
}

type pathGroup struct {
	Path   string
	Routes []Route
}

type routeExtension struct {
	Method  string `yaml:"method"`
	Path    string `yaml:"path"`
	Auth    string `yaml:"auth"`
	Proxy   string `yaml:"proxy"`
	Pattern string `yaml:"pattern"`
}

func groupByOpenAPIPath(routes []Route) ([]pathGroup, error) {
	var out []pathGroup
	index := map[string]int{}
	seenMethod := map[string]bool{}
	for _, rt := range routes {
		if rt.Method == "" || rt.Pattern == "" || rt.Handler == nil {
			return nil, fmt.Errorf("incomplete route %s %s", rt.Method, rt.Pattern)
		}
		switch rt.Auth {
		case AuthPublic, AuthEmbed, AuthAuthenticated:
		default:
			return nil, fmt.Errorf("route %s %s has auth %q", rt.Method, rt.Pattern, rt.Auth)
		}
		switch rt.Proxy {
		case ProxyBrowser, ProxyNone:
		default:
			return nil, fmt.Errorf("route %s %s has proxy %q", rt.Method, rt.Pattern, rt.Proxy)
		}
		key := rt.Method + " " + rt.Pattern
		if seenMethod[key] {
			return nil, fmt.Errorf("duplicate route %s", key)
		}
		seenMethod[key] = true
		p := rt.OpenAPIPath()
		if i, ok := index[p]; ok {
			prev := out[i].Routes[0].SpecRef
			if prev != rt.SpecRef {
				return nil, fmt.Errorf("path %s mixes spec refs %q and %q", p, prev, rt.SpecRef)
			}
			out[i].Routes = append(out[i].Routes, rt)
			continue
		}
		index[p] = len(out)
		out = append(out, pathGroup{Path: p, Routes: []Route{rt}})
	}
	return out, nil
}

func renderRouteExtensions(routes []Route) (string, error) {
	rows := make([]routeExtension, 0, len(routes))
	for _, rt := range routes {
		rows = append(rows, routeExtension{
			Method:  rt.Method,
			Path:    rt.OpenAPIPath(),
			Auth:    string(rt.Auth),
			Proxy:   string(rt.Proxy),
			Pattern: rt.Pattern,
		})
	}
	raw, err := marshalIndent(rows)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(generatedBegin)
	b.WriteString("# Generated from the mux route table. Do not edit.\n")
	b.WriteString("# Regenerate: go run ./cmd/genroutes\n")
	b.WriteString("x-flowforge-route-table:\n")
	b.WriteString("  generated: true\n")
	b.WriteString("  source: apps/api/internal/httpapi/routes.go\n")
	b.WriteString("x-flowforge-routes:\n")
	for _, line := range strings.Split(strings.TrimRight(string(raw), "\n"), "\n") {
		b.WriteString("  ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString(generatedEnd)
	return b.String(), nil
}

func renderGeneratedPath(g pathGroup) (string, error) {
	ref := g.Routes[0].SpecRef
	if ref != "" {
		if strings.ContainsAny(g.Path, "\n:#") || strings.ContainsAny(ref, "\n") {
			return "", fmt.Errorf("path %s has an unsafe spec ref", g.Path)
		}
		return fmt.Sprintf("  %s:\n    $ref: %q\n", g.Path, ref), nil
	}
	item := &yaml.Node{Kind: yaml.MappingNode}
	if err := fillPathItem(item, g.Routes); err != nil {
		return "", err
	}
	return encodePathBlock(g.Path, item)
}

func fillPathItem(dst *yaml.Node, routes []Route) error {
	if outsideAPI(routes[0].Pattern) {
		node, err := unmarshalNode("- url: \"/\"\n  description: \"Mounted at the origin root, outside the /api/v1 prefix.\"\n")
		if err != nil {
			return err
		}
		dst.Content = append(dst.Content, scalar("servers"), node)
	}
	for _, rt := range routes {
		op, err := stubOperation(rt)
		if err != nil {
			return err
		}
		dst.Content = append(dst.Content, scalar(strings.ToLower(rt.Method)), op)
	}
	return nil
}

func stubOperation(rt Route) (*yaml.Node, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "operationId: %s\n", operationID(rt.Method, rt.OpenAPIPath()))
	fmt.Fprintf(&b, "summary: %s %s\n", rt.Method, rt.OpenAPIPath())
	b.WriteString("description: |\n")
	fmt.Fprintf(&b, "  Generated from the route table (%s %s).\n", rt.Method, rt.Pattern)
	fmt.Fprintf(&b, "  Auth class: %s. Identity proxy: %s.\n", rt.Auth, rt.Proxy)
	b.WriteString("  Responses never include secrets, credentials, tokens, private keys, or vault material.\n")
	b.WriteString("  Vault references are display name and UUID only.\n")
	b.WriteString("responses:\n")
	b.WriteString("  \"200\":\n")
	b.WriteString("    description: Success\n")
	if rt.Auth == AuthAuthenticated {
		b.WriteString("  \"401\":\n")
		b.WriteString("    $ref: \"#/components/responses/Unauthenticated\"\n")
		b.WriteString("  \"403\":\n")
		b.WriteString("    $ref: \"#/components/responses/Forbidden\"\n")
	}
	b.WriteString("  \"405\":\n")
	b.WriteString("    $ref: \"#/components/responses/MethodNotAllowed\"\n")
	b.WriteString("  \"500\":\n")
	b.WriteString("    $ref: \"#/components/responses/InternalError\"\n")
	return unmarshalNode(b.String())
}

func operationID(method, path string) string {
	var b strings.Builder
	b.WriteString(strings.ToLower(method))
	for _, part := range strings.Split(strings.Trim(path, "/"), "/") {
		part = strings.Trim(part, "{}")
		for _, seg := range strings.FieldsFunc(part, func(r rune) bool { return r == '-' || r == '_' }) {
			if seg == "" {
				continue
			}
			b.WriteString(strings.ToUpper(seg[:1]))
			b.WriteString(seg[1:])
		}
	}
	return b.String()
}

func encodePathBlock(path string, item *yaml.Node) (string, error) {
	root := &yaml.Node{Kind: yaml.MappingNode}
	root.Content = []*yaml.Node{scalar(path), item}
	raw, err := marshalNode(root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimRight(string(raw), "\n"), "\n") {
		if line == "" {
			b.WriteByte('\n')
			continue
		}
		b.WriteString("  ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func proxySegments(rt Route) []string {
	path := strings.TrimPrefix(rt.OpenAPIPath(), "/")
	if path == "" {
		return nil
	}
	return strings.Split(path, "/")
}

func paramKinds(segments []string) map[string]string {
	out := map[string]string{}
	for _, seg := range segments {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") && len(seg) > 2 {
			name := seg[1 : len(seg)-1]
			out[name] = paramKind(name)
		}
	}
	return out
}

func paramKind(name string) string {
	switch name {
	case "key":
		return "segment"
	case "triggerId":
		return "trigger"
	default:
		return "uuid"
	}
}

func outsideAPI(pattern string) bool {
	return pattern != "/api/v1" && !strings.HasPrefix(pattern, "/api/v1/")
}

func scalar(v string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v}
}

func unmarshalNode(src string) (*yaml.Node, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
		return nil, err
	}
	if len(doc.Content) != 1 {
		return nil, fmt.Errorf("expected one yaml node")
	}
	return doc.Content[0], nil
}

func marshalIndent(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func marshalNode(n *yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(n); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func normalizeDocument(raw []byte) (string, error) {
	text := strings.TrimRight(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n") + "\n"
	root, err := rootMapping(text, "document.yaml")
	if err != nil {
		return "", err
	}
	keys := mappingKeys(root)
	for _, forbidden := range []string{"paths", "components", "x-flowforge-routes", "x-flowforge-route-table"} {
		if keys[forbidden] {
			return "", fmt.Errorf("document.yaml must not contain %s", forbidden)
		}
	}
	for _, required := range []string{"openapi", "info", "servers"} {
		if !keys[required] {
			return "", fmt.Errorf("document.yaml missing %s", required)
		}
	}
	return text, nil
}

func normalizeComponents(raw []byte) (string, error) {
	text := strings.TrimRight(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n") + "\n"
	root, err := rootMapping(text, "components.yaml")
	if err != nil {
		return "", err
	}
	if len(root.Content) != 2 || root.Content[0].Value != "components" || root.Content[1].Kind != yaml.MappingNode {
		return "", fmt.Errorf("components.yaml must contain only a components mapping")
	}
	return text, nil
}

func assertPathItemRefs(groups []pathGroup, components string) error {
	root, err := rootMapping(components, "components.yaml")
	if err != nil {
		return err
	}
	comps := root.Content[1]
	var pathItems *yaml.Node
	for i := 0; i < len(comps.Content); i += 2 {
		if comps.Content[i].Value == "pathItems" {
			pathItems = comps.Content[i+1]
			break
		}
	}
	have := map[string]bool{}
	if pathItems != nil && pathItems.Kind == yaml.MappingNode {
		for i := 0; i < len(pathItems.Content); i += 2 {
			have[pathItems.Content[i].Value] = true
		}
	}
	const prefix = "#/components/pathItems/"
	for _, g := range groups {
		ref := g.Routes[0].SpecRef
		if ref == "" {
			continue
		}
		name, ok := strings.CutPrefix(ref, prefix)
		if !ok || name == "" || strings.Contains(name, "/") || !have[name] {
			return fmt.Errorf("path %s spec ref %s is not in components.pathItems", g.Path, ref)
		}
	}
	return nil
}

func rootMapping(text, name string) (*yaml.Node, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(text), &doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", name, err)
	}
	if len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, fmt.Errorf("%s root must be a mapping", name)
	}
	return doc.Content[0], nil
}

func mappingKeys(root *yaml.Node) map[string]bool {
	keys := map[string]bool{}
	for i := 0; i < len(root.Content); i += 2 {
		keys[root.Content[i].Value] = true
	}
	return keys
}
