package httpapi

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	generatedBegin = "# BEGIN generated-route-table\n"
	generatedEnd   = "# END generated-route-table\n"
)

// RenderOpenAPI rebuilds the published spec so its path inventory and
// x-flowforge-routes classification match the route table. Operation prose
// is kept when the method set for that path is unchanged. Paths the route
// table does not register are dropped. Missing paths and methods are stubs
// that carry no secret examples.
func RenderOpenAPI(routes []Route, existing []byte) ([]byte, error) {
	text := strings.ReplaceAll(string(existing), "\r\n", "\n")
	pathsAt, err := column0Offset(text, "paths:")
	if err != nil {
		return nil, err
	}
	componentsAt, err := column0Offset(text, "components:")
	if err != nil {
		return nil, err
	}
	if componentsAt <= pathsAt {
		return nil, fmt.Errorf("openapi components key must follow paths")
	}
	componentsLine := strings.Count(text[:componentsAt], "\n") + 1

	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(text), &doc); err != nil {
		return nil, fmt.Errorf("parse openapi: %w", err)
	}
	pathsNode, err := mappingValue(doc.Content[0], "paths")
	if err != nil {
		return nil, err
	}

	lines := strings.Split(text, "\n")
	blocks := map[string]string{}
	var existingOrder []string
	for i := 0; i < len(pathsNode.Content); i += 2 {
		key := pathsNode.Content[i]
		start := key.Line
		end := componentsLine
		if i+2 < len(pathsNode.Content) {
			end = pathsNode.Content[i+2].Line
		}
		if start < 1 || end > len(lines)+1 || start >= end {
			return nil, fmt.Errorf("bad span for path %s", key.Value)
		}
		block := strings.TrimRight(strings.Join(lines[start-1:end-1], "\n"), "\n")
		blocks[key.Value] = block
		existingOrder = append(existingOrder, key.Value)
	}

	groups, err := groupByOpenAPIPath(routes)
	if err != nil {
		return nil, err
	}
	byPath := map[string]pathGroup{}
	var routeOrder []string
	for _, g := range groups {
		byPath[g.Path] = g
		routeOrder = append(routeOrder, g.Path)
	}

	var b strings.Builder
	preamble := stripGenerated(text[:pathsAt])
	b.WriteString(strings.TrimRight(preamble, "\n"))
	b.WriteByte('\n')
	ext, err := renderRouteExtensions(routes)
	if err != nil {
		return nil, err
	}
	b.WriteString(ext)
	b.WriteString("paths:\n")

	seen := map[string]bool{}
	for _, path := range existingOrder {
		g, ok := byPath[path]
		if !ok {
			continue
		}
		seen[path] = true
		block, err := renderPath(path, blocks[path], g.Routes)
		if err != nil {
			return nil, err
		}
		b.WriteString(block)
		b.WriteByte('\n')
	}
	for _, path := range routeOrder {
		if seen[path] {
			continue
		}
		block, err := renderPath(path, "", byPath[path].Routes)
		if err != nil {
			return nil, err
		}
		b.WriteString(block)
		b.WriteByte('\n')
	}
	components := text[componentsAt:]
	if !strings.HasPrefix(components, "components:") {
		return nil, fmt.Errorf("components slice does not start at the key")
	}
	if !strings.HasSuffix(components, "\n") {
		components += "\n"
	}
	b.WriteString(components)
	return []byte(b.String()), nil
}

// RenderProxyAllowlist renders the browser identity-proxy allowlist.
// Only ProxyBrowser routes are included. Parameter match kinds:
// uuid (default), segment ({key}), trigger ({triggerId}: UUID or wh_ public id).
func RenderProxyAllowlist(routes []Route) ([]byte, error) {
	type group struct {
		pattern []string
		methods []string
		auth    AuthClass
		params  map[string]string
	}
	var order []string
	groups := map[string]*group{}
	for _, rt := range routes {
		if rt.Proxy != ProxyBrowser {
			continue
		}
		segs := proxySegments(rt)
		params := paramKinds(segs)
		key := strings.Join(segs, "/")
		g := groups[key]
		if g == nil {
			g = &group{pattern: segs, auth: rt.Auth, params: params}
			groups[key] = g
			order = append(order, key)
		}
		if g.auth != rt.Auth {
			return nil, fmt.Errorf("proxy pattern %s mixes auth %s and %s", key, g.auth, rt.Auth)
		}
		g.methods = append(g.methods, rt.Method)
	}

	var b strings.Builder
	b.WriteString("// Code generated by `go run ./cmd/genroutes` from the API route table. DO NOT EDIT.\n\n")
	b.WriteString("export type ProxyAuth = \"public\" | \"embed\" | \"authenticated\";\n\n")
	b.WriteString("export type ProxyParam = \"uuid\" | \"segment\" | \"trigger\";\n\n")
	b.WriteString("export type GeneratedProxyRoute = {\n")
	b.WriteString("  readonly methods: readonly string[];\n")
	b.WriteString("  readonly pattern: readonly string[];\n")
	b.WriteString("  readonly auth: ProxyAuth;\n")
	b.WriteString("  readonly params: Readonly<Record<string, ProxyParam>>;\n")
	b.WriteString("};\n\n")
	b.WriteString("export const GENERATED_PROXY_ROUTES: readonly GeneratedProxyRoute[] = [\n")
	for _, key := range order {
		g := groups[key]
		b.WriteString("  {\n")
		b.WriteString("    methods: [")
		for i, m := range g.methods {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", m))
		}
		b.WriteString("],\n")
		b.WriteString("    pattern: [")
		for i, p := range g.pattern {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", p))
		}
		b.WriteString("],\n")
		b.WriteString(fmt.Sprintf("    auth: %q,\n", g.auth))
		b.WriteString("    params: {")
		names := make([]string, 0, len(g.params))
		for name := range g.params {
			names = append(names, name)
		}
		sort.Strings(names)
		for i, name := range names {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%s: %q", name, g.params[name]))
		}
		b.WriteString("},\n")
		b.WriteString("  },\n")
	}
	b.WriteString("];\n")
	return []byte(b.String()), nil
}

type pathGroup struct {
	Path   string
	Routes []Route
}

type routeExtension struct {
	Method  string `yaml:"method"`
	Path    string `yaml:"path"`
	Auth    string `yaml:"auth"`
	Proxy   string `yaml:"proxy"`
	Pattern string `yaml:"pattern"`
}

func groupByOpenAPIPath(routes []Route) ([]pathGroup, error) {
	var out []pathGroup
	index := map[string]int{}
	seenMethod := map[string]bool{}
	for _, rt := range routes {
		if rt.Method == "" || rt.Pattern == "" || rt.Handler == nil {
			return nil, fmt.Errorf("incomplete route %s %s", rt.Method, rt.Pattern)
		}
		switch rt.Auth {
		case AuthPublic, AuthEmbed, AuthAuthenticated:
		default:
			return nil, fmt.Errorf("route %s %s has auth %q", rt.Method, rt.Pattern, rt.Auth)
		}
		switch rt.Proxy {
		case ProxyBrowser, ProxyNone:
		default:
			return nil, fmt.Errorf("route %s %s has proxy %q", rt.Method, rt.Pattern, rt.Proxy)
		}
		key := rt.Method + " " + rt.Pattern
		if seenMethod[key] {
			return nil, fmt.Errorf("duplicate route %s", key)
		}
		seenMethod[key] = true
		p := rt.OpenAPIPath()
		if i, ok := index[p]; ok {
			prev := out[i].Routes[0].SpecRef
			if prev != rt.SpecRef {
				return nil, fmt.Errorf("path %s mixes spec refs %q and %q", p, prev, rt.SpecRef)
			}
			out[i].Routes = append(out[i].Routes, rt)
			continue
		}
		index[p] = len(out)
		out = append(out, pathGroup{Path: p, Routes: []Route{rt}})
	}
	return out, nil
}

func renderRouteExtensions(routes []Route) (string, error) {
	rows := make([]routeExtension, 0, len(routes))
	for _, rt := range routes {
		rows = append(rows, routeExtension{
			Method:  rt.Method,
			Path:    rt.OpenAPIPath(),
			Auth:    string(rt.Auth),
			Proxy:   string(rt.Proxy),
			Pattern: rt.Pattern,
		})
	}
	raw, err := marshalIndent(rows)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(generatedBegin)
	b.WriteString("# Generated from the mux route table. Do not edit.\n")
	b.WriteString("# Regenerate: go run ./cmd/genroutes\n")
	b.WriteString("x-flowforge-route-table:\n")
	b.WriteString("  generated: true\n")
	b.WriteString("  source: apps/api/internal/httpapi/routes.go\n")
	b.WriteString("x-flowforge-routes:\n")
	for _, line := range strings.Split(strings.TrimRight(string(raw), "\n"), "\n") {
		b.WriteString("  ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString(generatedEnd)
	return b.String(), nil
}

func renderPath(path, existing string, routes []Route) (string, error) {
	if existing != "" {
		methods, ref, item, err := inspectPathBlock(existing)
		if err != nil {
			return "", fmt.Errorf("%s: %w", path, err)
		}
		if ref != "" {
			want := routes[0].SpecRef
			if want == "" || want != ref {
				return "", fmt.Errorf("%s: spec ref %q, route table wants %q", path, ref, want)
			}
			for _, rt := range routes {
				if rt.SpecRef != ref {
					return "", fmt.Errorf("%s: inconsistent spec ref", path)
				}
			}
			return existing, nil
		}
		if sameMethods(methods, routes) {
			return existing, nil
		}
		rebuilt, err := rebuildPathItem(path, item, routes)
		if err != nil {
			return "", err
		}
		return rebuilt, nil
	}
	item := &yaml.Node{Kind: yaml.MappingNode}
	if err := fillPathItem(item, nil, routes); err != nil {
		return "", err
	}
	return encodePathBlock(path, item)
}

func inspectPathBlock(block string) (methods []string, ref string, item *yaml.Node, err error) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(block), &doc); err != nil {
		return nil, "", nil, err
	}
	if len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode || len(doc.Content[0].Content) != 2 {
		return nil, "", nil, fmt.Errorf("path block must contain one path key")
	}
	item = doc.Content[0].Content[1]
	if item.Kind != yaml.MappingNode {
		return nil, "", nil, fmt.Errorf("path item must be a mapping")
	}
	for i := 0; i < len(item.Content); i += 2 {
		k := item.Content[i].Value
		if k == "$ref" {
			ref = item.Content[i+1].Value
			continue
		}
		if isHTTPMethod(k) {
			methods = append(methods, strings.ToUpper(k))
		}
	}
	return methods, ref, item, nil
}

func sameMethods(have []string, routes []Route) bool {
	if len(have) != len(routes) {
		return false
	}
	got := map[string]int{}
	for _, m := range have {
		got[m]++
	}
	for _, rt := range routes {
		got[rt.Method]--
		if got[rt.Method] < 0 {
			return false
		}
	}
	for _, n := range got {
		if n != 0 {
			return false
		}
	}
	return true
}

func rebuildPathItem(path string, item *yaml.Node, routes []Route) (string, error) {
	next := &yaml.Node{Kind: yaml.MappingNode}
	if err := fillPathItem(next, item, routes); err != nil {
		return "", err
	}
	return encodePathBlock(path, next)
}

func fillPathItem(dst, src *yaml.Node, routes []Route) error {
	ops := map[string]*yaml.Node{}
	if src != nil {
		for i := 0; i < len(src.Content); i += 2 {
			k := src.Content[i].Value
			if isHTTPMethod(k) {
				ops[strings.ToUpper(k)] = src.Content[i+1]
				continue
			}
			if k == "$ref" {
				continue
			}
			dst.Content = append(dst.Content, src.Content[i], src.Content[i+1])
		}
	}
	if outsideAPI(routes[0].Pattern) && !hasKey(dst, "servers") {
		node, err := unmarshalNode("- url: \"/\"\n  description: \"Mounted at the origin root, outside the /api/v1 prefix.\"\n")
		if err != nil {
			return err
		}
		dst.Content = append(dst.Content, scalar("servers"), node)
	}
	for _, rt := range routes {
		op := ops[rt.Method]
		if op == nil {
			var err error
			op, err = stubOperation(rt)
			if err != nil {
				return err
			}
		}
		dst.Content = append(dst.Content, scalar(strings.ToLower(rt.Method)), op)
	}
	return nil
}

func stubOperation(rt Route) (*yaml.Node, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "operationId: %s\n", operationID(rt.Method, rt.OpenAPIPath()))
	fmt.Fprintf(&b, "summary: %s %s\n", rt.Method, rt.OpenAPIPath())
	b.WriteString("description: |\n")
	fmt.Fprintf(&b, "  Generated from the route table (%s %s).\n", rt.Method, rt.Pattern)
	fmt.Fprintf(&b, "  Auth class: %s. Identity proxy: %s.\n", rt.Auth, rt.Proxy)
	b.WriteString("  Responses never include secrets, credentials, tokens, private keys, or vault material.\n")
	b.WriteString("  Vault references are display name and UUID only.\n")
	b.WriteString("responses:\n")
	b.WriteString("  \"200\":\n")
	b.WriteString("    description: Success\n")
	if rt.Auth == AuthAuthenticated {
		b.WriteString("  \"401\":\n")
		b.WriteString("    $ref: \"#/components/responses/Unauthenticated\"\n")
		b.WriteString("  \"403\":\n")
		b.WriteString("    $ref: \"#/components/responses/Forbidden\"\n")
	}
	b.WriteString("  \"405\":\n")
	b.WriteString("    $ref: \"#/components/responses/MethodNotAllowed\"\n")
	b.WriteString("  \"500\":\n")
	b.WriteString("    $ref: \"#/components/responses/InternalError\"\n")
	return unmarshalNode(b.String())
}

func operationID(method, path string) string {
	var b strings.Builder
	b.WriteString(strings.ToLower(method))
	for _, part := range strings.Split(strings.Trim(path, "/"), "/") {
		part = strings.Trim(part, "{}")
		for _, seg := range strings.FieldsFunc(part, func(r rune) bool { return r == '-' || r == '_' }) {
			if seg == "" {
				continue
			}
			b.WriteString(strings.ToUpper(seg[:1]))
			b.WriteString(seg[1:])
		}
	}
	return b.String()
}

func encodePathBlock(path string, item *yaml.Node) (string, error) {
	root := &yaml.Node{Kind: yaml.MappingNode}
	root.Content = []*yaml.Node{scalar(path), item}
	raw, err := marshalNode(root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimRight(string(raw), "\n"), "\n") {
		if line == "" {
			b.WriteByte('\n')
			continue
		}
		b.WriteString("  ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
	return strings.TrimRight(b.String(), "\n"), nil
}

func proxySegments(rt Route) []string {
	path := strings.TrimPrefix(rt.OpenAPIPath(), "/")
	if path == "" {
		return nil
	}
	return strings.Split(path, "/")
}

func paramKinds(segments []string) map[string]string {
	out := map[string]string{}
	for _, seg := range segments {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") && len(seg) > 2 {
			name := seg[1 : len(seg)-1]
			out[name] = paramKind(name)
		}
	}
	return out
}

func paramKind(name string) string {
	switch name {
	case "key":
		return "segment"
	case "triggerId":
		return "trigger"
	default:
		return "uuid"
	}
}

func outsideAPI(pattern string) bool {
	return pattern != "/api/v1" && !strings.HasPrefix(pattern, "/api/v1/")
}

func isHTTPMethod(k string) bool {
	switch strings.ToUpper(k) {
	case httpMethodGet, httpMethodPost, httpMethodPut, httpMethodPatch, httpMethodDelete, "HEAD", "OPTIONS":
		return true
	default:
		return false
	}
}

const (
	httpMethodGet    = "GET"
	httpMethodPost   = "POST"
	httpMethodPut    = "PUT"
	httpMethodPatch  = "PATCH"
	httpMethodDelete = "DELETE"
)

func hasKey(n *yaml.Node, key string) bool {
	for i := 0; i < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			return true
		}
	}
	return false
}

func scalar(v string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v}
}

func unmarshalNode(src string) (*yaml.Node, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
		return nil, err
	}
	if len(doc.Content) != 1 {
		return nil, fmt.Errorf("expected one yaml node")
	}
	return doc.Content[0], nil
}

func marshalIndent(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func marshalNode(n *yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(n); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func column0Offset(text, key string) (int, error) {
	if strings.HasPrefix(text, key+"\n") {
		return 0, nil
	}
	needle := "\n" + key + "\n"
	at := strings.Index(text, needle)
	if at < 0 {
		return 0, fmt.Errorf("openapi missing %s", key)
	}
	return at + 1, nil
}

func mappingValue(root *yaml.Node, key string) (*yaml.Node, error) {
	if root == nil || root.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("openapi root is not a mapping")
	}
	for i := 0; i < len(root.Content); i += 2 {
		if root.Content[i].Value == key {
			return root.Content[i+1], nil
		}
	}
	return nil, fmt.Errorf("openapi missing %s", key)
}

func stripGenerated(preamble string) string {
	for {
		i := strings.Index(preamble, generatedBegin)
		if i < 0 {
			return preamble
		}
		j := strings.Index(preamble[i:], generatedEnd)
		if j < 0 {
			return preamble[:i]
		}
		preamble = preamble[:i] + preamble[i+j+len(generatedEnd):]
	}
}
