apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowforge
resources:
  - namespace.yaml
  - api-configmap.yaml
  - api-secret.example.yaml
  - api-deployment.yaml
  - api-service.yaml
  - default-deny-networkpolicy.yaml
  - api-networkpolicy.yaml
  - postgres-networkpolicy.yaml
  - ingress.yaml
