apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowforge
resources:
  - namespace.yaml
  - api-configmap.yaml
  - api-secret.example.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-pdb.yaml
  - api-hpa.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-pdb.yaml
  - web-hpa.yaml
  - runner-deployment.yaml
  - runner-pdb.yaml
  - runner-hpa.yaml
  - script-runner-rbac.yaml
  - backup-secret.example.yaml
  - backup-cronjob.yaml
  - pitr-base-cronjob.yaml
  - wal-archive-deployment.yaml
  - default-deny-networkpolicy.yaml
  - api-networkpolicy.yaml
  - web-networkpolicy.yaml
  - runner-networkpolicy.yaml
  - backup-networkpolicy.yaml
  - postgres-networkpolicy.yaml
  - ingress.yaml
